language: python
python:
- '3.3'
- '3.4'
- '3.5'
install:
- pip install --upgrade pip
- pip install .[lint,test]
before_script:
- flake8 buzz
- flake8 tests
script: py.test tests
deploy:
  provider: pypi
  user: dusktreader
  password:
    secure: AsdgPMLdi+CGB1qxKk7lvs3lBv/t08+ejEpgifUaxjLatSgScMQlytxKkqRoCTlIETUhrTJYW7Q/Tg670637ub0WazNYphOZz1EOhnxvJn1CuwPI97agGcvkLcldt3a4v0jHSCUQRXWj55bK355o7R+SFITQAVnoZe6ot6CoAGhrrSKnAdGx9qOekqMI9wl15bLInoqp3/kepOnJXhZkUJO2xsIGBRUq2l3ittJxJoRdy6S7o2F4W6Egbrl9toOCADjifEXh81sxBiu2eC0FM9MQjZ8IPbcyfk1fiR8AjiDqfRhflexBCtLdYRPGg2m9zYhrj/nTbOIjiS2VBfG+NcrI3k4pUfEG3etmk0pToBFF0OM14Rtg0NW+ZaI5eNfVGajD0uyKcl9fHs9Bm1PSW5U75C9NwWDY7zLLz7TWB/aCcvi9zauknc3NUUIiMy7gwU4D237VL49i2P+ATiC5JhfiixF0RQl75AfXmJkx90dGrglKkMp25hkGutI15O8/hDKBmNp4mPCrzhU6at1EBiAqNCO8I8zr42i8gBpM/QNiEuTf07/RrVMPG/FwH3p3vhh5TZADrF5r162qUba6EeXfl2UkqUYlln00Dxoo5QC0KAWmxjOLVgZqrpsx95HwzupkZk9t1WdBg/+Cdu5w6TckkR3+Qlyh8Q0ULcOYI8o=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: dusktreader/py-buzz
